// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main application service for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";

/**
 * GetAutoStartStatus returns whether autostart is enabled
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStartStatus() {
    return $Call.ByID(651686285);
}

/**
 * GetConfig returns the current configuration
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(3902498144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetPrinters returns a list of available printers
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPrinters() {
    return $Call.ByID(2234194827).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IsServerRunning returns whether the server is running
 * @returns {$CancellablePromise<boolean>}
 */
export function IsServerRunning() {
    return $Call.ByID(288755184);
}

/**
 * MinimizeToTray hides the window (background mode)
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeToTray() {
    return $Call.ByID(1496580499);
}

/**
 * PrintTestPage prints a test page to verify printer is working
 * @returns {$CancellablePromise<void>}
 */
export function PrintTestPage() {
    return $Call.ByID(2070912382);
}

/**
 * QuitApp exits the application completely
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3291959616);
}

/**
 * SaveConfig saves the configuration
 * @param {string} printerName
 * @param {number} port
 * @param {boolean} autoStartEnabled
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(printerName, port, autoStartEnabled) {
    return $Call.ByID(2775748437, printerName, port, autoStartEnabled);
}

/**
 * SetAutoStart enables or disables autostart
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(3275390879, enabled);
}

/**
 * ShowWindow shows the main window
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(3051797087);
}

/**
 * Shutdown is called when the app is closing
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(780008012);
}

/**
 * StartServer starts the print server
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function StartServer(port) {
    return $Call.ByID(1606237317, port);
}

/**
 * StopServer stops the print server
 * @returns {$CancellablePromise<void>}
 */
export function StopServer() {
    return $Call.ByID(3981686469);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Array($Create.Any);
